# Generated by Django 4.0.3 on 2022-03-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Село', 'verbose_name_plural': 'Село'},
        ),
        migrations.AlterField(
            model_name='needy',
            name='status',
            field=models.CharField(blank=True, choices=[('Получили помощь', 'Получили помощь'), ('В разработке', 'В разработке'), ('Не полученные', 'Не полученные')], max_length=255, null=True, verbose_name='Стадия помощи'),
        ),
    ]
