# Generated by Django 4.0.3 on 2022-04-02 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Лат'),
        ),
        migrations.AddField(
            model_name='family',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Лат'),
        ),
        migrations.AddField(
            model_name='family',
            name='main_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='main.needy', verbose_name='Отбасының үлкені'),
        ),
    ]
