# Generated by Django 4.0.3 on 2022-04-02 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('main', '0002_family_lat_family_lng_family_main_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='eldimeken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.localities', verbose_name='Аулды округ'),
        ),
    ]
