# Generated by Django 4.0.3 on 2022-04-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_needy_lat_needy_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needy',
            name='lng',
        ),
        migrations.AddField(
            model_name='needy',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='needy',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
