# Generated by Django 4.0.3 on 2022-04-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_needy_lng_needy_lon_alter_needy_lat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, default=43.0401635, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='needy',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=15, default=69.3886292, max_digits=19, null=True),
        ),
    ]
