# Generated by Django 4.0.3 on 2022-03-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_needy_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='needy/', verbose_name='Сүреті'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='needies', to='main.statustype'),
        ),
    ]
