# Generated by Django 4.0.3 on 2022-03-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_needy_image_alter_needy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='cash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Салынған ақша'),
        ),
    ]
