# Generated by Django 4.0.3 on 2022-03-28 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_needy_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needy',
            name='cash',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Салынған ақша')),
                ('created_at', models.DateTimeField()),
                ('type', models.CharField(blank=True, choices=[('Аударылды', 'Аударылды'), ('Берілді', 'Берілді')], max_length=255, null=True, verbose_name='Тип')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
