# Generated by Django 4.0.3 on 2022-03-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_event_needy_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cash',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='Салынған ақша'),
        ),
    ]
