# Generated by Django 4.0.3 on 2022-03-28 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_needy_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Оқиға', 'verbose_name_plural': 'Оқигалар'},
        ),
        migrations.AlterModelOptions(
            name='needy',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявкалар'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Ауылды округ', 'verbose_name_plural': 'Ауылды округтар'},
        ),
        migrations.AlterModelOptions(
            name='statushome',
            options={'verbose_name': 'Үйінің жағдайы', 'verbose_name_plural': 'Үйінің жағдайы'},
        ),
        migrations.AlterModelOptions(
            name='statustype',
            options={'verbose_name': 'Статус жағдайы', 'verbose_name_plural': 'Статус жағдайлары'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AlterField(
            model_name='event',
            name='cash',
            field=models.IntegerField(blank=True, null=True, verbose_name='Салынған ақша'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Мекенжайы'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='changed_onwer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changed_owner', to=settings.AUTH_USER_MODEL, verbose_name='Заявканы өзгерткен адам'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='childTotal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Балалар саны'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Пікір'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Жасалғвн кұні'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='getHelp',
            field=models.TextField(blank=True, null=True, verbose_name='Қандай көмек алды'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='iin',
            field=models.CharField(max_length=12, verbose_name='ЖСН'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Аты'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Заявканы ашқан адам'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='period',
            field=models.DateField(blank=True, null=True, verbose_name='Көмек алудың соңғы мерзімі'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Телефон нөмірі'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.region', verbose_name='Аулды округ'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='needies', to='main.statustype', verbose_name='Статус жағдайы'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='statusHome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.statushome', verbose_name='Үйінің жағдайы'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='surName',
            field=models.CharField(max_length=255, verbose_name='Тегі'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='typeHelp',
            field=models.TextField(blank=True, null=True, verbose_name='Қандай көмек қажет'),
        ),
    ]
