# Generated by Django 4.0.3 on 2022-03-28 23:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_event_options_alter_needy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Жасалған кұні'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='needies', to='main.statustype', verbose_name='Статус жағдайы'),
            preserve_default=False,
        ),
    ]
