# Generated by Django 4.0.3 on 2022-03-28 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_needy_created_at_alter_needy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='canJob',
            field=models.CharField(blank=True, choices=[('Жұмысқа жарамды', 'Жұмысқа жарамды'), ('Жұмысы жарамсыз', 'Жұмысы жарамсыз')], max_length=255, verbose_name='Жұмыс тұрағы'),
        ),
        migrations.AddField(
            model_name='needy',
            name='hasJob',
            field=models.CharField(choices=[('Жұмысқа жарамды', 'Жұмысқа жарамды'), ('Жұмысы жарамсыз', 'Жұмысы жарамсыз')], max_length=255, null=True, verbose_name='Жұмыс тұрағы'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категориясы'),
        ),
    ]
