# Generated by Django 4.0.3 on 2022-03-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_needy_canjob_needy_hasjob_alter_needy_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='hasJob',
            field=models.CharField(choices=[('Жұмысы бар', 'Жұмысы бар'), ('Жұмысы жоқ', 'Жұмысы жоқ')], max_length=255, null=True, verbose_name='Жұмыс тұрағы'),
        ),
    ]
