# Generated by Django 4.0.3 on 2022-03-28 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_alter_needy_hasjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='needy_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
