# Generated by Django 4.0.3 on 2022-03-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_event_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needy',
            name='name',
        ),
        migrations.RemoveField(
            model_name='needy',
            name='surName',
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Аударылды', 'Аударылды'), ('Берілді', 'Берілді'), ('Жеке аударылды', 'Жеке аударылды')], max_length=255, null=True, verbose_name='Тип'),
        ),
    ]
