# Generated by Django 4.0.3 on 2022-03-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_needy_name_remove_needy_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Аты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='needy',
            name='surName',
            field=models.CharField(default=1, max_length=255, verbose_name='Тегі'),
            preserve_default=False,
        ),
    ]
