# Generated by Django 4.0.3 on 2022-03-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_needy_name_needy_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='canJob',
            field=models.CharField(blank=True, choices=[('Жұмысқа жарамды', 'Жұмысқа жарамды'), ('Жұмысы жарамсыз', 'Жұмысы жарамсыз')], max_length=255, null=True, verbose_name='Жұмыс тұрағы'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='hasJob',
            field=models.CharField(blank=True, choices=[('Жұмысы бар', 'Жұмысы бар'), ('Жұмысы жоқ', 'Жұмысы жоқ')], max_length=255, null=True, verbose_name='Жұмыс тұрағы'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аты'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='surName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі'),
        ),
    ]
