# Generated by Django 4.0.3 on 2022-03-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Аты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='surName',
            field=models.CharField(default=1, max_length=255, verbose_name='Тегі'),
            preserve_default=False,
        ),
    ]
